import { useState } from 'react';
import { Plus, Download, Undo2, FilePlus2, Trash2 } from 'lucide-react';
import { api, msg, inr, fmtDate, fmtTime, download } from '../api';
import { useLoad, Loading, PageHeader, Badge, Empty, Modal, Field, toast, Table, Tabs } from '../components/ui';

export default function FeeAdmin() {
  const [tab, setTab] = useState('structures'); const [q, setQ] = useState('');
  const st = useLoad(() => api.get('/fees/structures').then((r) => r.data), []);
  const inv = useLoad(() => api.get('/fees/invoices', { params: { q } }).then((r) => r.data), [q]);
  const rf = useLoad(() => api.get('/fees/refunds').then((r) => r.data), []);
  const settings = useLoad(() => api.get('/settings').then((r) => r.data), []);
  const [open, setOpen] = useState(false); const [f, setF] = useState({ session: '', roomType: '', category: 'All', amount: '', installments: 1, dueDate: '', sessionStart: '' }); const [refund, setRefund] = useState(null); const [rd, setRd] = useState({ amount: '', reason: '', cancelInvoice: false });
  const create = async () => { try { await api.post('/fees/structures', f); toast.ok('Fee structure saved'); setOpen(false); st.reload(); } catch (e) { toast.err(msg(e)); } };
  const del = async (s) => { try { await api.delete(`/fees/structures/${s._id}`); st.reload(); } catch (e) { toast.err(msg(e)); } };
  const gen = async () => { try { const r = await api.post('/fees/invoices/generate'); toast.ok(`${r.data.created} invoice(s) generated`); inv.reload(); } catch (e) { toast.err(msg(e)); } };
  const doRefund = async () => { try { await api.post('/fees/refund', { invoiceId: refund._id, ...rd }); toast.ok('Refund recorded'); setRefund(null); inv.reload(); rf.reload(); } catch (e) { toast.err(msg(e)); } };
  const dup = async (id) => { try { const r = await api.post(`/fees/receipts/${id}/duplicate`); await download(`/fees/receipts/${r.data._id}/pdf`, `${r.data.number}.pdf`); } catch (e) { toast.err(msg(e)); } };
  if (st.loading || !inv.data) return <Loading />;
  return (<><PageHeader title="Fees" subtitle="Fee structures apply only to sessions that have not started. Late fee is set under Settings." actions={tab === 'structures' ? <button className="btn-primary" onClick={() => { setF({ ...f, session: settings.data?.session || '' }); setOpen(true); }}><Plus size={16} />New fee structure</button> : tab === 'invoices' && <button className="btn-outline" onClick={gen}><FilePlus2 size={16} />Generate missing invoices</button>} />
    <Tabs tabs={[{ id: 'structures', label: 'Fee structures' }, { id: 'invoices', label: 'Invoices' }, { id: 'refunds', label: 'Refunds' }]} value={tab} onChange={setTab} />
    {tab === 'structures' && <Table head={['Session', 'Room type', 'Category', 'Amount', 'Installments', 'Due date', 'Session starts', '']} empty={st.data.length ? null : <Empty title="No fee structures yet" hint="Create one per room type. Invoices are generated automatically when a room is allotted." />}>
      {st.data.map((s) => <tr key={s._id}><td className="td">{s.session}</td><td className="td font-semibold">{s.roomType}</td><td className="td">{s.category}</td><td className="td">{inr(s.amount)}</td><td className="td">{s.installments}</td><td className="td">{fmtDate(s.dueDate)}</td><td className="td">{fmtDate(s.sessionStart)}</td><td className="td text-right"><button className="text-slate-400 hover:text-red-600" aria-label="Delete" onClick={() => del(s)}><Trash2 size={16} /></button></td></tr>)}</Table>}
    {tab === 'invoices' && <><input className="input mb-4 max-w-sm" placeholder="Search student or invoice" value={q} onChange={(e) => setQ(e.target.value)} /><Table head={['Invoice', 'Student', 'Billed', 'Paid', 'Balance', 'Due', 'Status', '']} empty={inv.data.length ? null : <Empty title="No invoices" />}>
      {inv.data.map((i) => <tr key={i._id}><td className="td font-semibold">{i.invoiceNo}</td><td className="td">{i.student?.name}<p className="text-xs text-slate-500">{i.student?.username?.toUpperCase()}</p></td><td className="td">{inr(i.total + i.lateFee)}</td><td className="td">{inr(i.paid)}</td><td className="td">{inr(i.balance)}</td><td className="td">{fmtDate(i.dueDate)}</td><td className="td"><Badge>{i.status}</Badge></td><td className="td text-right">{i.paid > 0 && i.status !== 'Cancelled' && <button className="btn-outline !py-1.5" onClick={() => { setRefund(i); setRd({ amount: i.paid, reason: '', cancelInvoice: false }); }}><Undo2 size={15} />Refund</button>}</td></tr>)}</Table></>}
    {tab === 'refunds' && <Table head={['Date', 'Student', 'Invoice', 'Amount', 'Reference', 'Reason']} empty={rf.data?.length ? null : <Empty title="No refunds recorded" />}>{(rf.data || []).map((r) => <tr key={r._id}><td className="td">{fmtTime(r.createdAt)}</td><td className="td">{r.student?.name}</td><td className="td">{r.invoice?.invoiceNo}</td><td className="td">{inr(r.amount)}</td><td className="td font-mono text-xs">{r.txnRef}</td><td className="td">{r.reason}</td></tr>)}</Table>}
    <Modal open={open} onClose={() => setOpen(false)} title="New fee structure" footer={<><button className="btn-outline" onClick={() => setOpen(false)}>Cancel</button><button className="btn-primary" onClick={create}>Save</button></>}>
      <div className="grid gap-4 sm:grid-cols-2"><Field label="Session" required><input className="input" placeholder="2026-27" value={f.session} onChange={(e) => setF({ ...f, session: e.target.value })} /></Field><Field label="Room type" required><input className="input" placeholder="Double" value={f.roomType} onChange={(e) => setF({ ...f, roomType: e.target.value })} /></Field>
        <Field label="Category"><select className="input" value={f.category} onChange={(e) => setF({ ...f, category: e.target.value })}><option>All</option><option>General</option><option>Reserved</option></select></Field><Field label="Amount (₹)" required><input type="number" min="0" className="input" value={f.amount} onChange={(e) => setF({ ...f, amount: e.target.value })} /></Field>
        <Field label="Installments"><select className="input" value={f.installments} onChange={(e) => setF({ ...f, installments: e.target.value })}>{[1, 2, 3].map((n) => <option key={n}>{n}</option>)}</select></Field><Field label="Session start date" required hint="Must be in the future."><input type="date" className="input" value={f.sessionStart} onChange={(e) => setF({ ...f, sessionStart: e.target.value })} /></Field>
        <Field label="Payment due date" required className="sm:col-span-2"><input type="date" className="input" value={f.dueDate} onChange={(e) => setF({ ...f, dueDate: e.target.value })} /></Field></div></Modal>
    <Modal open={!!refund} onClose={() => setRefund(null)} title={`Refund ${refund?.invoiceNo}`} footer={<><button className="btn-outline" onClick={() => setRefund(null)}>Cancel</button><button className="btn-primary" onClick={doRefund}>Record refund</button></>}>
      <div className="space-y-4"><Field label={`Amount (paid so far ${inr(refund?.paid)})`} required><input type="number" className="input" value={rd.amount} onChange={(e) => setRd({ ...rd, amount: e.target.value })} /></Field><Field label="Reason" required><input className="input" placeholder="Overpayment, cancelled allocation…" value={rd.reason} onChange={(e) => setRd({ ...rd, reason: e.target.value })} /></Field><label className="flex items-center gap-2 text-sm"><input type="checkbox" className="accent-brand-600" checked={rd.cancelInvoice} onChange={(e) => setRd({ ...rd, cancelInvoice: e.target.checked })} />Cancel the invoice (allocation cancelled)</label></div></Modal></>);
}
