import { useState } from 'react';
import { Plus, Search, KeyRound } from 'lucide-react';
import { api, msg } from '../api';
import { useLoad, Loading, PageHeader, Badge, Empty, Modal, Field, toast, Table, Tabs } from '../components/ui';

const blank = { name: '', username: '', email: '', password: '', role: 'student', phone: '', department: '', year: '', blocks: '' };
export default function Users() {
  const [role, setRole] = useState(''); const [q, setQ] = useState(''); const [edit, setEdit] = useState(null); const [f, setF] = useState(blank); const [pw, setPw] = useState(null); const [np, setNp] = useState('');
  const { data, loading, reload } = useLoad(() => api.get('/users', { params: { role, q } }).then((r) => r.data), [role, q]);
  const open = (u) => { setEdit(u || {}); setF(u ? { ...u, blocks: (u.blocks || []).join(', ') } : blank); };
  const save = async () => { const body = { ...f, blocks: String(f.blocks || '').split(',').map((b) => b.trim()).filter(Boolean) }; try { if (edit._id) await api.put(`/users/${edit._id}`, body); else await api.post('/users', body); toast.ok('User saved'); setEdit(null); reload(); } catch (e) { toast.err(msg(e)); } };
  const toggle = async (u) => { try { await api.put(`/users/${u._id}`, { active: !u.active }); reload(); } catch (e) { toast.err(msg(e)); } };
  const setPass = async () => { try { await api.post(`/users/${pw._id}/password`, { password: np }); toast.ok('Password set'); setPw(null); setNp(''); } catch (e) { toast.err(msg(e)); } };
  return (<><PageHeader title="Users & roles" subtitle="Create accounts, change roles, set disciplinary holds and block assignments." actions={<button className="btn-primary" onClick={() => open()}><Plus size={16} />Add user</button>} />
    <Tabs tabs={[{ id: '', label: 'Everyone' }, { id: 'student', label: 'Students' }, { id: 'warden', label: 'Wardens' }, { id: 'staff', label: 'Hostel staff' }, { id: 'admin', label: 'Admins' }]} value={role} onChange={setRole} />
    <div className="relative mb-4 max-w-sm"><Search size={16} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400" /><input className="input pl-10" placeholder="Search name, ID or e-mail" value={q} onChange={(e) => setQ(e.target.value)} /></div>
    {loading ? <Loading /> : <Table head={['User', 'Role', 'Contact', 'Flags', 'Status', '']} empty={data.length ? null : <Empty title="No users found" />}>
      {data.map((u) => <tr key={u._id}><td className="td"><p className="font-semibold">{u.name}</p><p className="text-xs text-slate-500">{u.username.toUpperCase()}</p></td><td className="td capitalize">{u.role === 'staff' ? 'Hostel staff' : u.role}</td><td className="td text-xs">{u.email}<br />{u.phone}</td><td className="td">{u.disciplinaryHold && <Badge color="red">Disciplinary hold</Badge>}{u.role === 'warden' && <span className="text-xs text-slate-500">{u.blocks?.length ? `Blocks ${u.blocks.join(', ')}` : 'All blocks'}</span>}</td>
        <td className="td"><Badge color={u.active ? 'green' : 'gray'}>{u.active ? 'Active' : 'Deactivated'}</Badge></td><td className="td"><div className="flex justify-end gap-2"><button className="btn-outline !py-1.5" onClick={() => open(u)}>Edit</button><button className="btn-outline !px-2.5 !py-1.5" title="Set password" onClick={() => setPw(u)}><KeyRound size={15} /></button><button className="btn-outline !py-1.5" onClick={() => toggle(u)}>{u.active ? 'Deactivate' : 'Activate'}</button></div></td></tr>)}</Table>}
    <Modal open={!!edit} wide onClose={() => setEdit(null)} title={edit?._id ? `Edit ${edit.name}` : 'Add user'} footer={<><button className="btn-outline" onClick={() => setEdit(null)}>Cancel</button><button className="btn-primary" onClick={save}>Save</button></>}>
      <div className="grid gap-4 sm:grid-cols-2"><Field label="Full name" required><input className="input" value={f.name} onChange={(e) => setF({ ...f, name: e.target.value })} /></Field><Field label="Login ID" required><input className="input" disabled={!!edit?._id} value={f.username} onChange={(e) => setF({ ...f, username: e.target.value })} /></Field>
        <Field label="E-mail" required><input className="input" type="email" value={f.email} onChange={(e) => setF({ ...f, email: e.target.value })} /></Field><Field label="Phone"><input className="input" value={f.phone || ''} onChange={(e) => setF({ ...f, phone: e.target.value })} /></Field>
        <Field label="Role" required><select className="input" value={f.role} onChange={(e) => setF({ ...f, role: e.target.value })}><option value="student">Student</option><option value="warden">Warden</option><option value="staff">Hostel staff</option><option value="admin">Administrator</option></select></Field>
        {!edit?._id && <Field label="Initial password" required><input className="input" type="password" value={f.password} onChange={(e) => setF({ ...f, password: e.target.value })} /></Field>}
        {f.role === 'student' && <><Field label="Department"><input className="input" value={f.department || ''} onChange={(e) => setF({ ...f, department: e.target.value })} /></Field><Field label="Year"><input className="input" value={f.year || ''} onChange={(e) => setF({ ...f, year: e.target.value })} /></Field>
          <Field label="Academic standing"><select className="input" value={f.academicStanding || 'Good standing'} onChange={(e) => setF({ ...f, academicStanding: e.target.value })}><option>Good standing</option><option>On probation</option><option>Backlogs pending</option></select></Field>
          <Field label="Disciplinary hold" hint="Blocks the student from applying."><select className="input" value={f.disciplinaryHold ? 'yes' : 'no'} onChange={(e) => setF({ ...f, disciplinaryHold: e.target.value === 'yes' })}><option value="no">No hold</option><option value="yes">On hold</option></select></Field>
          <Field label="Disciplinary note" className="sm:col-span-2"><input className="input" value={f.disciplinaryNote || ''} onChange={(e) => setF({ ...f, disciplinaryNote: e.target.value })} /></Field></>}
        {f.role === 'warden' && <Field label="Blocks managed" hint="Comma separated, e.g. A, B. Leave empty for all blocks." className="sm:col-span-2"><input className="input" value={f.blocks} onChange={(e) => setF({ ...f, blocks: e.target.value })} /></Field>}</div></Modal>
    <Modal open={!!pw} onClose={() => setPw(null)} title={`Set password for ${pw?.name}`} footer={<><button className="btn-outline" onClick={() => setPw(null)}>Cancel</button><button className="btn-primary" onClick={setPass}>Save password</button></>}><Field label="New password" hint="At least 8 characters."><input className="input" type="text" value={np} onChange={(e) => setNp(e.target.value)} /></Field></Modal></>);
}
