import { useState } from 'react';
import { Plus, LogIn, LogOut, Search, ShieldAlert, Copy, Camera } from 'lucide-react';
import { api, msg, fmtTime, fmtDate } from '../api';
import { useAuth } from '../auth';
import { useLoad, Loading, PageHeader, Badge, Empty, Modal, Field, toast, Table, Tabs, Confirm } from '../components/ui';

export default function Visitors() {
  const { user } = useAuth(); const role = user.role;
  return role === 'student' ? <Student /> : <Desk role={role} />;
}
function Student() {
  const { data, loading, reload } = useLoad(() => api.get('/visitors').then((r) => r.data), []);
  const [open, setOpen] = useState(false); const [f, setF] = useState({ name: '', phone: '', relationship: '', expectedDate: '', purpose: '' });
  const save = async () => { try { await api.post('/visitors', f); toast.ok('Visitor registered. Share the code at the gate.'); setOpen(false); setF({ name: '', phone: '', relationship: '', expectedDate: '', purpose: '' }); reload(); } catch (e) { toast.err(msg(e)); } };
  const cancel = async (id) => { try { await api.delete(`/visitors/${id}`); reload(); } catch (e) { toast.err(msg(e)); } };
  if (loading) return <Loading />;
  return (<><PageHeader title="Visitors" subtitle="Pre-register guests so the gate can let them in quickly." actions={<button className="btn-primary" onClick={() => setOpen(true)}><Plus size={16} />Register a visitor</button>} />
    <Table head={['Visitor', 'Visit date', 'Code', 'Status', '']} empty={data.length ? null : <Empty title="No visitors yet" hint="Register a visitor to get a code they can show at the gate." />}>
      {data.map((v) => <tr key={v._id}><td className="td"><p className="font-semibold">{v.name}</p><p className="text-xs text-slate-500">{v.relationship} · {v.phone}</p></td><td className="td">{fmtDate(v.expectedDate)}</td>
        <td className="td"><button className="inline-flex items-center gap-1.5 rounded-lg bg-mist px-2.5 py-1 font-mono text-xs font-semibold" onClick={() => { navigator.clipboard?.writeText(v.code); toast.ok('Code copied'); }}>{v.code}<Copy size={12} /></button></td>
        <td className="td"><Badge color={v.expired ? 'red' : undefined}>{v.expired ? 'Expired' : v.status}</Badge>{v.durationMin ? <span className="ml-2 text-xs text-slate-500">{v.durationMin} min</span> : null}</td>
        <td className="td text-right">{v.status === 'Registered' && <button className="text-sm font-semibold text-red-600" onClick={() => cancel(v._id)}>Cancel</button>}</td></tr>)}</Table>
    <Modal open={open} onClose={() => setOpen(false)} title="Register a visitor" footer={<><button className="btn-outline" onClick={() => setOpen(false)}>Cancel</button><button className="btn-primary" onClick={save}>Register</button></>}>
      <div className="grid gap-4 sm:grid-cols-2"><Field label="Visitor name" required className="sm:col-span-2"><input className="input" value={f.name} onChange={(e) => setF({ ...f, name: e.target.value })} /></Field><Field label="Phone" required><input className="input" value={f.phone} onChange={(e) => setF({ ...f, phone: e.target.value })} /></Field><Field label="Relationship" required><input className="input" placeholder="Parent, sibling…" value={f.relationship} onChange={(e) => setF({ ...f, relationship: e.target.value })} /></Field><Field label="Expected visit date" required><input type="date" className="input" min={new Date().toISOString().slice(0, 10)} value={f.expectedDate} onChange={(e) => setF({ ...f, expectedDate: e.target.value })} /></Field><Field label="Purpose"><input className="input" value={f.purpose} onChange={(e) => setF({ ...f, purpose: e.target.value })} /></Field></div></Modal></>);
}
function Desk({ role }) {
  const [tab, setTab] = useState(role === 'staff' ? 'gate' : 'log'); const [q, setQ] = useState(''); const [code, setCode] = useState(''); const [from, setFrom] = useState(''); const [to, setTo] = useState('');
  const inside = useLoad(() => api.get('/visitors', { params: { status: 'Inside' } }).then((r) => r.data), [], 20000);
  const expected = useLoad(() => api.get('/visitors', { params: { today: 1 } }).then((r) => r.data.filter((v) => v.status === 'Registered')), [], 30000);
  const alerts = useLoad(() => api.get('/visitors', { params: { alerts: 1 } }).then((r) => r.data), [], 30000);
  const approvals = useLoad(() => api.get('/visitors', { params: { approval: 1 } }).then((r) => r.data), [], 30000);
  const log = useLoad(() => api.get('/visitors', { params: { q, from, to } }).then((r) => r.data), [q, from, to]);
  const [warn, setWarn] = useState(null); const [walk, setWalk] = useState(false);
  const all = () => { inside.reload(); expected.reload(); alerts.reload(); approvals.reload(); log.reload(); };
  const enter = async (body, force) => {
    try { await api.post('/visitors/entry', { ...body, force: force ? 'true' : undefined }); toast.ok('Entry recorded'); setCode(''); setWarn(null); all(); }
    catch (e) { const d = e.response?.data; if (d?.code) setWarn({ ...d, body }); else toast.err(msg(e)); }
  };
  const exit = async (id) => { try { await api.post(`/visitors/${id}/exit`); toast.ok('Exit recorded'); all(); } catch (e) { toast.err(msg(e)); } };
  const approve = async (id) => { await api.post(`/visitors/${id}/approve`); toast.ok('Entry approved'); all(); };
  const reqApproval = async (id) => { try { await api.post(`/visitors/${id}/request-approval`); toast.ok('Warden has been notified'); setWarn(null); all(); } catch (e) { toast.err(msg(e)); } };
  const tabs = role === 'staff' ? [{ id: 'gate', label: 'Gate desk' }, { id: 'log', label: 'Visitor log' }] : [{ id: 'log', label: 'Visitor log' }, { id: 'alerts', label: 'Overstay alerts', count: alerts.data?.length }, { id: 'approvals', label: 'Approvals', count: approvals.data?.length }, { id: 'gate', label: 'Gate desk' }];
  return (<><PageHeader title={role === 'staff' ? 'Gate desk' : 'Visitor log'} subtitle="Entries, exits and alerts for the hostel premises." actions={<button className="btn-primary" onClick={() => setWalk(true)}><Plus size={16} />Walk-in visitor</button>} />
    <Tabs tabs={tabs} value={tab} onChange={setTab} />
    {tab === 'gate' && <div className="grid gap-6 lg:grid-cols-2">
      <div className="space-y-6"><div className="card p-5"><h3 className="mb-3 font-semibold">Confirm entry by code</h3><form className="flex gap-2" onSubmit={(e) => { e.preventDefault(); enter({ code }); }}><input className="input font-mono uppercase" placeholder="V-XXXXXX" value={code} onChange={(e) => setCode(e.target.value)} /><button className="btn-primary" disabled={!code}><LogIn size={16} />Enter</button></form></div>
        <div className="card p-5"><h3 className="mb-3 font-semibold">Expected today</h3>{expected.data?.length ? <ul className="divide-y divide-line">{expected.data.map((v) => <li key={v._id} className="flex items-center justify-between gap-3 py-2.5"><div><p className="text-sm font-semibold">{v.name}</p><p className="text-xs text-slate-500">for {v.student?.name} · {v.code}</p></div><button className="btn-soft !py-1.5" onClick={() => enter({ id: v._id })}>Enter</button></li>)}</ul> : <Empty title="Nobody expected" />}</div></div>
      <div className="card p-5"><h3 className="mb-3 font-semibold">Inside now ({inside.data?.length || 0})</h3>{inside.data?.length ? <ul className="divide-y divide-line">{inside.data.map((v) => <li key={v._id} className="flex items-center justify-between gap-3 py-2.5"><div><p className="text-sm font-semibold">{v.name}</p><p className="text-xs text-slate-500">for {v.student?.name} · since {fmtTime(v.entryAt)}</p></div><button className="btn-outline !py-1.5" onClick={() => exit(v._id)}><LogOut size={15} />Exit</button></li>)}</ul> : <Empty title="No visitors inside" />}</div>
    </div>}
    {tab === 'log' && <><div className="mb-4 flex flex-wrap gap-3"><div className="relative min-w-[220px] flex-1"><Search size={16} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400" /><input className="input pl-10" placeholder="Search visitor, student or code" value={q} onChange={(e) => setQ(e.target.value)} /></div><input type="date" className="input !w-auto" value={from} onChange={(e) => setFrom(e.target.value)} aria-label="From" /><input type="date" className="input !w-auto" value={to} onChange={(e) => setTo(e.target.value)} aria-label="To" /></div>
      {log.loading ? <Loading /> : <Table head={['Visitor', 'Visiting', 'Entry', 'Exit', 'Duration', 'Status']} empty={log.data?.length ? null : <Empty title="No visitor records" />}>{log.data.map((v) => <tr key={v._id}><td className="td"><p className="font-semibold">{v.name}</p><p className="text-xs text-slate-500">{v.kind === 'WalkIn' ? 'Walk-in' : 'Pre-registered'} · {v.code}</p></td><td className="td">{v.student?.name}</td><td className="td">{fmtTime(v.entryAt)}</td><td className="td">{fmtTime(v.exitAt)}</td><td className="td">{v.durationMin ? `${v.durationMin} min` : '-'}</td><td className="td"><Badge>{v.status}</Badge></td></tr>)}</Table>}</>}
    {tab === 'alerts' && <div className="card divide-y divide-line">{alerts.data?.length ? alerts.data.map((v) => <div key={v._id} className="flex items-center justify-between gap-3 px-5 py-4"><div className="flex items-center gap-3"><ShieldAlert className="text-red-600" size={20} /><div><p className="text-sm font-semibold">{v.name} is past visiting hours</p><p className="text-xs text-slate-500">Visiting {v.student?.name} · entered {fmtTime(v.entryAt)}</p></div></div><button className="btn-outline" onClick={() => exit(v._id)}>Record exit</button></div>) : <Empty title="No overstays" hint="Visitors still inside after visiting hours appear here." />}</div>}
    {tab === 'approvals' && <div className="card divide-y divide-line">{approvals.data?.length ? approvals.data.map((v) => <div key={v._id} className="flex items-center justify-between gap-3 px-5 py-4"><div><p className="text-sm font-semibold">{v.name}</p><p className="text-xs text-slate-500">for {v.student?.name} · {v.code}</p></div><button className="btn-primary" onClick={() => approve(v._id)}>Approve entry</button></div>) : <Empty title="Nothing waiting" hint="Entries outside visiting hours or with expired passes need your approval." />}</div>}
    <Modal open={!!warn} onClose={() => setWarn(null)} title={warn?.code === 'LIMIT' ? 'Visitor limit reached' : warn?.code === 'OUT_OF_HOURS' ? 'Outside visiting hours' : 'Pre-registration expired'} footer={<><button className="btn-outline" onClick={() => setWarn(null)}>Close</button>{warn?.code === 'LIMIT' ? <button className="btn-primary" onClick={() => enter(warn.body, true)}>Allow anyway</button> : role === 'staff' ? <button className="btn-primary" onClick={() => reqApproval(warn.visitorId)}>Ask warden to approve</button> : <button className="btn-primary" onClick={async () => { await approve(warn.visitorId); enter(warn.body); }}>Approve and enter</button>}</>}><p className="text-sm text-slate-600">{warn?.message}</p></Modal>
    <Walk open={walk} onClose={() => setWalk(false)} done={() => { setWalk(false); all(); }} />
  </>);
}
function Walk({ open, onClose, done }) {
  const [f, setF] = useState({ name: '', phone: '', idType: 'Aadhaar', idNumber: '', purpose: '', relationship: '' }); const [stu, setStu] = useState(null); const [q, setQ] = useState(''); const [list, setList] = useState([]); const [photo, setPhoto] = useState(null); const [dup, setDup] = useState('');
  const search = async (v) => { setQ(v); if (v.length > 1) setList((await api.get('/users/lookup', { params: { q: v } })).data); else setList([]); };
  const submit = async (force) => {
    const fd = new FormData(); Object.entries({ ...f, studentId: stu?._id, enter: 'true', force: force ? 'true' : '' }).forEach(([k, v]) => fd.append(k, v)); if (photo) fd.append('photo', photo);
    try { await api.post('/visitors/walkin', fd); toast.ok('Visitor registered and entry recorded'); setDup(''); done(); }
    catch (e) { const d = e.response?.data; if (d?.code === 'DUPLICATE_INSIDE') setDup(d.message); else if (d?.code) { toast.ok('Registered. ' + d.message); done(); } else toast.err(msg(e)); }
  };
  return <Modal open={open} onClose={onClose} title="Walk-in visitor" wide footer={<><button className="btn-outline" onClick={onClose}>Cancel</button><button className="btn-primary" disabled={!stu} onClick={() => submit(false)}>Register and enter</button></>}>
    {dup && <div className="mb-4 rounded-xl bg-amber-50 p-4 text-sm text-amber-800 ring-1 ring-amber-200">{dup} <button className="ml-2 font-semibold underline" onClick={() => submit(true)}>Register anyway</button></div>}
    <div className="grid gap-4 sm:grid-cols-2">
      <Field label="Student being visited" required className="sm:col-span-2">{stu ? <div className="flex items-center justify-between rounded-xl bg-brand-50 px-4 py-2.5 text-sm"><span><b>{stu.name}</b> · {stu.username.toUpperCase()}</span><button className="font-semibold text-brand-700" onClick={() => setStu(null)}>Change</button></div> : <div className="relative"><input className="input" placeholder="Search by name or registration number" value={q} onChange={(e) => search(e.target.value)} />{list.length > 0 && <ul className="absolute z-10 mt-1 w-full overflow-hidden rounded-xl border border-line bg-white shadow-lift">{list.map((s) => <li key={s._id}><button className="block w-full px-4 py-2.5 text-left text-sm hover:bg-brand-50" onClick={() => { setStu(s); setList([]); }}>{s.name} <span className="text-slate-500">· {s.username.toUpperCase()} · {s.department}</span></button></li>)}</ul>}</div>}</Field>
      <Field label="Visitor name" required><input className="input" value={f.name} onChange={(e) => setF({ ...f, name: e.target.value })} /></Field><Field label="Phone" required><input className="input" value={f.phone} onChange={(e) => setF({ ...f, phone: e.target.value })} /></Field>
      <Field label="ID proof type" required><select className="input" value={f.idType} onChange={(e) => setF({ ...f, idType: e.target.value })}>{['Aadhaar', 'Driving licence', 'Voter ID', 'Passport', 'PAN'].map((t) => <option key={t}>{t}</option>)}</select></Field><Field label="ID number" required><input className="input" value={f.idNumber} onChange={(e) => setF({ ...f, idNumber: e.target.value })} /></Field>
      <Field label="Relationship"><input className="input" value={f.relationship} onChange={(e) => setF({ ...f, relationship: e.target.value })} /></Field><Field label="Purpose"><input className="input" value={f.purpose} onChange={(e) => setF({ ...f, purpose: e.target.value })} /></Field>
      <Field label="Visitor photo" className="sm:col-span-2" hint="Capture with the device camera or upload (JPEG/PNG, 2 MB)."><label className="btn-outline cursor-pointer"><Camera size={16} />{photo ? photo.name : 'Take or choose photo'}<input type="file" accept="image/*" capture="environment" className="sr-only" onChange={(e) => setPhoto(e.target.files[0])} /></label></Field></div></Modal>;
}
