import { useState } from 'react';
import { Plus, Camera } from 'lucide-react';
import { api, msg, fmtTime } from '../api';
import { useAuth } from '../auth';
import { useLoad, Loading, PageHeader, Badge, Empty, Modal, Field, toast, Table, Tabs } from '../components/ui';

export default function WorkOrders() {
  const { user } = useAuth(); const manager = ['warden', 'admin'].includes(user.role); const [tab, setTab] = useState(''); const [open, setOpen] = useState(false); const [done, setDone] = useState(null); const [rem, setRem] = useState(''); const [photos, setPhotos] = useState([]);
  const [f, setF] = useState({ complaintId: '', title: '', description: '', location: '', priority: 'Medium', assignedTo: '' });
  const { data, loading, reload } = useLoad(() => api.get('/workorders', { params: tab ? { status: tab } : {} }).then((r) => r.data), [tab], 30000);
  const staff = useLoad(() => (manager ? api.get('/users/staff').then((r) => r.data) : Promise.resolve([])), []);
  const conv = useLoad(() => (manager ? api.get('/workorders/convertible').then((r) => r.data) : Promise.resolve([])), [open]);
  const create = async () => { try { await api.post('/workorders', f); toast.ok('Work order created'); setOpen(false); setF({ complaintId: '', title: '', description: '', location: '', priority: 'Medium', assignedTo: '' }); reload(); } catch (e) { toast.err(msg(e)); } };
  const update = async (w, status, remarks) => { const fd = new FormData(); fd.append('status', status); if (remarks) fd.append('remarks', remarks); photos.forEach((p) => fd.append('photos', p)); try { await api.post(`/workorders/${w._id}/update`, fd); toast.ok(status === 'Completed' ? 'Marked complete. The student has been notified.' : 'Marked in progress'); setDone(null); setRem(''); setPhotos([]); reload(); } catch (e) { toast.err(msg(e)); } };
  const patch = async (w, body) => { try { await api.put(`/workorders/${w._id}`, body); reload(); } catch (e) { toast.err(msg(e)); } };
  const pick = (id) => { const c = conv.data?.find((x) => x._id === id); setF({ ...f, complaintId: id, title: c ? `Complaint #${c.number}` : '', description: c?.description || '', location: c?.room ? `${c.room.block}-${c.room.number}` : '' }); };
  return (<>
    <PageHeader title={manager ? 'Work orders' : 'My work orders'} subtitle="Maintenance tasks, with priority and status." actions={manager && <button className="btn-primary" onClick={() => setOpen(true)}><Plus size={16} />New work order</button>} />
    <Tabs tabs={[{ id: '', label: 'All' }, { id: 'Open', label: 'Open' }, { id: 'In Progress', label: 'In progress' }, { id: 'Completed', label: 'Completed' }]} value={tab} onChange={setTab} />
    {loading ? <Loading /> : <Table head={['Work order', 'Location', 'Priority', 'Assigned to', 'Status', '']} empty={data.length ? null : <Empty title="No work orders" hint={manager ? 'Create one directly or convert a Maintenance complaint.' : 'Work assigned to you appears here.'} />}>
      {data.map((w) => <tr key={w._id}><td className="td"><p className="font-semibold">#{w.number} {w.title}</p><p className="text-xs text-slate-500">{w.complaint ? `From complaint #${w.complaint.number} · ` : ''}{fmtTime(w.createdAt)}</p></td><td className="td">{w.location || '-'}</td>
        <td className="td">{manager && w.status !== 'Completed' ? <select className="input !w-28 !py-1.5" value={w.priority} onChange={(e) => patch(w, { priority: e.target.value })}>{['Low', 'Medium', 'High', 'Urgent'].map((p) => <option key={p}>{p}</option>)}</select> : <Badge>{w.priority}</Badge>}{w.overdue && <span className="ml-2"><Badge color="red">Overdue</Badge></span>}</td>
        <td className="td">{manager && w.status !== 'Completed' ? <select className="input !w-40 !py-1.5" value={w.assignedTo?._id || ''} onChange={(e) => patch(w, { assignedTo: e.target.value })}><option value="">Unassigned</option>{(staff.data || []).map((s) => <option key={s._id} value={s._id}>{s.name}</option>)}</select> : w.assignedTo?.name || '-'}</td><td className="td"><Badge>{w.status}</Badge></td>
        <td className="td"><div className="flex justify-end gap-2">{w.status !== 'Completed' && w.assignedTo && (!manager || user.role === 'admin' || true) && <>{w.status === 'Open' && <button className="btn-outline !py-1.5" onClick={() => update(w, 'In Progress')}>Start</button>}<button className="btn-primary !py-1.5" onClick={() => setDone(w)}>Complete</button></>}</div></td></tr>)}</Table>}
    <Modal open={open} onClose={() => setOpen(false)} title="New work order" footer={<><button className="btn-outline" onClick={() => setOpen(false)}>Cancel</button><button className="btn-primary" onClick={create}>Create</button></>}>
      <div className="space-y-4"><Field label="Convert a maintenance complaint" hint="Optional. Links the work order to the student's complaint."><select className="input" value={f.complaintId} onChange={(e) => pick(e.target.value)}><option value="">Not linked to a complaint</option>{(conv.data || []).map((c) => <option key={c._id} value={c._id}>#{c.number} · {c.description.slice(0, 50)}</option>)}</select></Field>
        <Field label="Title" required><input className="input" value={f.title} onChange={(e) => setF({ ...f, title: e.target.value })} /></Field><Field label="Description"><textarea rows={2} className="input" value={f.description} onChange={(e) => setF({ ...f, description: e.target.value })} /></Field>
        <div className="grid gap-4 sm:grid-cols-3"><Field label="Location"><input className="input" value={f.location} onChange={(e) => setF({ ...f, location: e.target.value })} /></Field><Field label="Priority"><select className="input" value={f.priority} onChange={(e) => setF({ ...f, priority: e.target.value })}>{['Low', 'Medium', 'High', 'Urgent'].map((p) => <option key={p}>{p}</option>)}</select></Field><Field label="Assign to"><select className="input" value={f.assignedTo} onChange={(e) => setF({ ...f, assignedTo: e.target.value })}><option value="">Later</option>{(staff.data || []).map((s) => <option key={s._id} value={s._id}>{s.name}</option>)}</select></Field></div></div></Modal>
    <Modal open={!!done} onClose={() => setDone(null)} title={`Complete #${done?.number}`} footer={<><button className="btn-outline" onClick={() => setDone(null)}>Cancel</button><button className="btn-primary" onClick={() => update(done, 'Completed', rem)}>Mark completed</button></>}>
      <div className="space-y-4"><Field label="Completion remarks" required><textarea rows={3} className="input" value={rem} onChange={(e) => setRem(e.target.value)} /></Field><Field label="Photos of the finished work" hint="Optional, up to 3."><label className="btn-outline cursor-pointer"><Camera size={16} />{photos.length ? `${photos.length} selected` : 'Add photos'}<input type="file" multiple accept="image/jpeg,image/png" className="sr-only" onChange={(e) => setPhotos([...e.target.files].slice(0, 3))} /></label></Field></div></Modal></>);
}
